name: Python CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: create environment with conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: conda-forge,bioconda
          auto-activate-base: false
          activate-environment: pytest_env
          environment-file: pytest_env.yml
      
      - name: check solution
        run: |
          conda env export

      - name: Run tests
        run: |
          pytest
