name: Python CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: create environment with conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: pytest_env
          environment-file: environment.yml
          auto-activate-base: false

      - name: check solution
        run: |
          conda env export

      - name: list all conda envs
        run: |
          conda env list
